//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doTimeTable {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("doTimeTable.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timetable ähnelt.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name ähnelt.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sum of all teachers hours per week (={0}) is less the sum of all needed hours in classes (={1}) ähnelt.
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum number of hours in subject {0} (={1}) is larger than the total maximum number of hours (={2}) ähnelt.
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teacher-to-Class ähnelt.
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Teacher to Class assignment ähnelt.
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Edit preset assignment of teachers and subject to classes&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Here you can edit predefined assignments of teachers and their subjects to classes.&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;Empty or the teacher who will teach this class in this subject ähnelt.
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;Non editable fields or columns with gray background are teacher or subjects which are part of the saved data but not in the current teacher or subject list. These columns are not checked and not saved. ähnelt.
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No classes, teachers or subjects are defined, nothing to do here. ähnelt.
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not enough teacher hours (={0]) for subject {1}. Needed {2} hours. ähnelt.
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Projects available. First create a new project by adding a new name into an empty row. ähnelt.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sum of needed hours (={0}) for subject {1} and teacher {2} is larger than the maximum hours (={3}) for this teacher. ähnelt.
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class-to-Subject ähnelt.
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit presets of classes and subjects to schedule ähnelt.
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Edit preset assignments of classes and subjects to each other and to schedule&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Here you can edit predefined assignments of classes and subjects to each other, i.e. the connected classes should have the given subject at the same time, and you can set the scheduled time of this subject for these connected classes or a single class.&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;ConnectionID&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;An arbitrary but unique ID, which must be repeated for every connected class. ähnelt.
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The subject of the connected classes; must be equal for every single ConnectionID ähnelt.
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;Day&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The scheduled day for this connection; can be empty; must be equal for every single ConnectionID ähnelt.
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;Hour&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The scheduled hour for this connection; can be empty; must be equal for every single ConnectionID ähnelt.
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No classes or subjects are defined, nothing to do here. ähnelt.
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example: ähnelt.
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classes 1a and 1b will have Sports at the same time. ähnelt.
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classes 2a and 2b will have Sports at Monday to the third and fourth hour. ähnelt.
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For each ConnectionID every class can only be called once. ähnelt.
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For each ConnectionID only one subject can be given. ähnelt.
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For each ConnectionID only one timepoint can be given. Day and hour must both be empty or both not empty. ähnelt.
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate timetable ähnelt.
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click Yes to abort the current calculation! ähnelt.
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running Calculation ähnelt.
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data has not been saved, see log window ähnelt.
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General calculation state: ähnelt.
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current progress value in %: ähnelt.
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation progress ähnelt.
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not enough teacher hours to fill all courses ähnelt.
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of teacher hours is low for subject ähnelt.
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following issues may lead to very long calculation time: ähnelt.
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My new project ähnelt.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some kind of description ähnelt.
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation date ähnelt.
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State ähnelt.
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View timetables ähnelt.
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timetable ähnelt.
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to teachers view ähnelt.
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to classes view ähnelt.
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A project needs a name ähnelt.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to default app ähnelt.
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No suitable timetable could be found! ähnelt.
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter ähnelt.
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Change parameters&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following parameter can be changed: ähnelt.
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;If teachers are attached to one or more specific classes, it can easily happen that a teachter is assigned to two classes at the same time.
        ///This is normally not allowed and a valid timetable can not be found.
        ///To deactivate this constraint this value can be set to non zero. ähnelt.
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The number of timetables to calculate. It is possible to calculate more than one timetable.
        ///Each timetable differs slightly. At least one timetable and maximal 10 will be calculated. ähnelt.
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No warnings. ähnelt.
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected projects? ähnelt.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random order ähnelt.
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export anonymised ähnelt.
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to export project. ähnelt.
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of project failed. ähnelt.
        /// </summary>
        internal static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The minimum backtrace counts to reach, before a warning is printed.
        ///While the timetable is being filled deadends may be reached where no more allocations are possible.
        ///In this case a step back is performed, called backtrace, and another combination is tried.
        ///If a specific combination of class and subject triggers a large number of backtraces, it is a hint on an unresolvable constraint.
        ///Only values from 10^i for i=1,2,3,4,5,6,7 are used (10,100,1000,...). ähnelt.
        /// </summary>
        internal static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following combination repeatedly results in unresolvable conflicts: ähnelt.
        /// </summary>
        internal static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The timetable is calculated for classes in order of the classes list.
        ///To change this to a random order of classes set this parameter to a value larger than 0. ähnelt.
        /// </summary>
        internal static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;Set this parameter to a value not 0 to allocate courses in the order of teacher coverage. The course with lowest coverage at first. ähnelt.
        /// </summary>
        internal static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit/Create ähnelt.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support, Questions and Discussion ähnelt.
        /// </summary>
        internal static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acknowledgement ähnelt.
        /// </summary>
        internal static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are using a free and unrestricted copy of doTimeTable ähnelt.
        /// </summary>
        internal static string String172 {
            get {
                return ResourceManager.GetString("String172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die doTimeTable is distributed under the GNU General Public License  (GPL) ähnelt.
        /// </summary>
        internal static string String173 {
            get {
                return ResourceManager.GetString("String173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please support the development of doTimeTable by purchasing a registration key ähnelt.
        /// </summary>
        internal static string String174 {
            get {
                return ResourceManager.GetString("String174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Julia script file can not be verified, aborting application. ähnelt.
        /// </summary>
        internal static string String175 {
            get {
                return ResourceManager.GetString("String175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Julia script file can not be verified.
        ///If you didn&apos;t change the file this may be a security thread.
        ///Choose Cancel to exit the application now. ähnelt.
        /// </summary>
        internal static string String176 {
            get {
                return ResourceManager.GetString("String176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security warning ähnelt.
        /// </summary>
        internal static string String177 {
            get {
                return ResourceManager.GetString("String177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration ID ähnelt.
        /// </summary>
        internal static string String178 {
            get {
                return ResourceManager.GetString("String178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download new version ähnelt.
        /// </summary>
        internal static string String179 {
            get {
                return ResourceManager.GetString("String179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subjects ähnelt.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install new version ähnelt.
        /// </summary>
        internal static string String180 {
            get {
                return ResourceManager.GetString("String180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No new version available ähnelt.
        /// </summary>
        internal static string String181 {
            get {
                return ResourceManager.GetString("String181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New version available ähnelt.
        /// </summary>
        internal static string String182 {
            get {
                return ResourceManager.GetString("String182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Julia dll file can not be verified, aborting application. ähnelt.
        /// </summary>
        internal static string String183 {
            get {
                return ResourceManager.GetString("String183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Julia dll file can not be verified.
        ///If you didn&apos;t change the file this may be a security thread.
        ///Choose Cancel to exit the application now. ähnelt.
        /// </summary>
        internal static string String184 {
            get {
                return ResourceManager.GetString("String184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy log to clipboard? ähnelt.
        /// </summary>
        internal static string String185 {
            get {
                return ResourceManager.GetString("String185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        internal static string String186 {
            get {
                return ResourceManager.GetString("String186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download running ähnelt.
        /// </summary>
        internal static string String187 {
            get {
                return ResourceManager.GetString("String187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current download in %: ähnelt.
        /// </summary>
        internal static string String188 {
            get {
                return ResourceManager.GetString("String188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verifying downloads ähnelt.
        /// </summary>
        internal static string String189 {
            get {
                return ResourceManager.GetString("String189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a single project ähnelt.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import registration key ähnelt.
        /// </summary>
        internal static string String190 {
            get {
                return ResourceManager.GetString("String190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The registration key is not valid ähnelt.
        /// </summary>
        internal static string String191 {
            get {
                return ResourceManager.GetString("String191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of registration key failed ähnelt.
        /// </summary>
        internal static string String192 {
            get {
                return ResourceManager.GetString("String192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration key is valid and installed ähnelt.
        /// </summary>
        internal static string String193 {
            get {
                return ResourceManager.GetString("String193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No major upgrades left for this registration ähnelt.
        /// </summary>
        internal static string String194 {
            get {
                return ResourceManager.GetString("String194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of major upgrades left for this registration ähnelt.
        /// </summary>
        internal static string String195 {
            get {
                return ResourceManager.GetString("String195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discard and close ähnelt.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check ähnelt.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save and close ähnelt.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit subjects ähnelt.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject name ähnelt.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Classes for Subject at once ähnelt.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max hours per day ähnelt.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sports ähnelt.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Subject Definition&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Here you define the subjects and their general time properties.&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Description of the columns meaning:&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;style type=&quot;text/css&quot;&gt;p{padding:0;margin:0;}&lt;/style&gt; ähnelt.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;&lt;li&gt;&lt;b&gt;Subject name&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;Max Classes for Subject at once&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;Max hours per day&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill in example data ähnelt.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Math ähnelt.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The name of the subject, e.g. math, sports, ... ähnelt.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;Not more than N classes at the same time, e.g. for sports only 2 classes can use  the sports hall together. ähnelt.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New project... ähnelt.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;Not more than N hours per day, e.g. math lessons should not be more than 2 hours a day for each class. ähnelt.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure to close the window? Changes will be lost. ähnelt.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data has been changed. ähnelt.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allowed values are ähnelt.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Values must be ähnelt.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column ähnelt.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Row ähnelt.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit classes ähnelt.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classes ähnelt.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Class definition and subjects hours per week&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project ähnelt.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Here you define the classes and how many hours of a subject they have per week.&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;&lt;li&gt;&lt;b&gt;Class name&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The name of the class, e.g. 1a, 1b, 2a, ... ähnelt.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;The following columns are subject names&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The number of hours per week for each subject and class ähnelt.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class name ähnelt.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;Non editable columns with gray background are subjects which are part of the saved classes but not in the current subject list. These columns are not checked and not saved. ähnelt.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data in gray columns will not be saved!
        ///Should we proceed? ähnelt.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This table is read only because another table is open for editing. ähnelt.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entries in this column must be positive integers or zero. ähnelt.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days and Hours ähnelt.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit days and hours ähnelt.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monday ähnelt.
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tuesday ähnelt.
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wednesday ähnelt.
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thursday ähnelt.
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friday ähnelt.
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturday ähnelt.
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sunday ähnelt.
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integer ähnelt.
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty ähnelt.
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zero ähnelt.
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unique ähnelt.
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positive ähnelt.
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not zero ähnelt.
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Days and Hours Definition&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Define the base structure of the timetable.&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;&lt;li&gt;&lt;b&gt;Days&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log ähnelt.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The days where the hours are allocated on ähnelt.
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;Hours&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The hours, which take place on every day ähnelt.
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/ul&gt; ähnelt.
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All days have the same numbers of hours. ähnelt.
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data has not been checked successfully. Save anyways? ähnelt.
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teacher ähnelt.
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit teacher ähnelt.
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teachers name ähnelt.
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max hours ähnelt.
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} can not be opened ähnelt.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;h3&gt;Edit your teachers&lt;/h3&gt; ähnelt.
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;Here you edit all your teachers and how many hours per week they are teaching in total and for each subject.&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;&lt;li&gt;&lt;b&gt;Teachers name&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The name of teacher ähnelt.
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;li&gt;&lt;b&gt;Max hours&lt;/b&gt;&lt;/li&gt; ähnelt.
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The maximum number of hours per week ähnelt.
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;br /&gt;The maximum number of hours per week for each subject. Zero or Empty if this teacher does not teach this subject. ähnelt.
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sum of all subject hours (={0}) is larger than the available hours per week (={1}) ähnelt.
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
