# This file is automatically generated in base/Makefile
const MACHINE = "x86_64-w64-mingw32"
const libm_name = "libopenlibm"
const libblas_name = "libopenblas64_"
const liblapack_name = "libopenblas64_"
const USE_BLAS64 = true
const USE_GPL_LIBS = true
const libllvm_version_string = "6.0.1"
const VERSION_STRING = "1.1.0"
const TAGGED_RELEASE_BANNER = "Official https://julialang.org/ release"
const SYSCONFDIR = "..\\etc"
const DATAROOTDIR = "..\\share"
const DOCDIR = "..\\share\\doc\\julia"
const LIBDIR = "..\\lib"
const PRIVATE_LIBDIR = "..\\lib\\julia"
const INCLUDEDIR = "..\\include"
