# This file was autogenerated in base/version_git.sh
struct GitVersionInfo
    commit::AbstractString
    commit_short::AbstractString
    branch::AbstractString
    build_number::Int
    date_string::AbstractString
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "80516ca20297a67b996caa08c38786332379b6a5",
    "80516ca202",
    "master",
    0,
    "2019-01-21 21:24 UTC",
    true,
    69,
    1544203235.
)
